# Introduction
This notebook sets up household electricity consumption data ready for exploratory analysis.
## To do list
1. Read in the data
2. Inspect the data
3. Correct and adjust the data
4. Save the data

# Read in the data

In [10]:
# Check file directory, navigate to the data directory and show contents
! ls
% cd ~/data
! ls

acorn_details.csv		 informations_households.csv
daily_dataset.zip		 smart-meters-in-london.zip
halfhourly_dataset.zip		 uk_bank_holidays.csv
hhblock_dataset.zip		 weather_daily_darksky.csv
household_power_consumption.txt  weather_hourly_darksky.csv
household_power_consumption.zip
/home/ubuntu/data
acorn_details.csv		 informations_households.csv
daily_dataset.zip		 smart-meters-in-london.zip
halfhourly_dataset.zip		 uk_bank_holidays.csv
hhblock_dataset.zip		 weather_daily_darksky.csv
household_power_consumption.txt  weather_hourly_darksky.csv
household_power_consumption.zip

In [9]:
import pandas as pd

# load all data
dataset = pd.read_csv('~/data/household_power_consumption.txt', sep=";", header=0, low_memory=False, infer_datetime_format=True, parse_dates={'datetime':[0,1]}, index_col=['datetime'])

In [22]:
# inspect the dataset
print(dataset.shape)
print(dataset.head())
dataset.dtypes

(2075259, 7)
                    Global_active_power Global_reactive_power  Voltage  \
datetime
2006-12-16 17:24:00               4.216                 0.418  234.840
2006-12-16 17:25:00               5.360                 0.436  233.630
2006-12-16 17:26:00               5.374                 0.498  233.290
2006-12-16 17:27:00               5.388                 0.502  233.740
2006-12-16 17:28:00               3.666                 0.528  235.680

                    Global_intensity Sub_metering_1 Sub_metering_2  \
datetime
2006-12-16 17:24:00           18.400          0.000          1.000
2006-12-16 17:25:00           23.000          0.000          1.000
2006-12-16 17:26:00           23.000          0.000          2.000
2006-12-16 17:27:00           23.000          0.000          1.000
2006-12-16 17:28:00           15.800          0.000          1.000

                     Sub_metering_3
datetime
2006-12-16 17:24:00            17.0
2006-12-16 17:25:00            16.0
2006-12-16 17:26:00            17.0
2006-12-16 17:27:00            17.0
2006-12-16 17:28:00            17.0

Global_active_power       object
Global_reactive_power     object
Voltage                   object
Global_intensity          object
Sub_metering_1            object
Sub_metering_2            object
Sub_metering_3           float64
dtype: object

In [25]:
dataset

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
datetime,,,,,,,
2006-12-16 17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
2006-12-16 17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2006-12-16 17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
2006-12-16 17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
2006-12-16 17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0
2006-12-16 17:29:00,3.520,0.522,235.020,15.000,0.000,2.000,17.0
2006-12-16 17:30:00,3.702,0.520,235.090,15.800,0.000,1.000,17.0
2006-12-16 17:31:00,3.700,0.520,235.220,15.800,0.000,1.000,17.0
2006-12-16 17:32:00,3.668,0.510,233.990,15.800,0.000,1.000,17.0
2006-12-16 17:33:00,3.662,0.510,233.860,15.800,0.000,2.000,16.0
2006-12-16 17:34:00,4.448,0.498,232.860,19.600,0.000,1.000,17.0
2006-12-16 17:35:00,5.412,0.470,232.780,23.200,0.000,1.000,17.0
2006-12-16 17:36:00,5.224,0.478,232.990,22.400,0.000,1.000,16.0
2006-12-16 17:37:00,5.268,0.398,232.910,22.600,0.000,2.000,17.0
2006-12-16 17:38:00,4.054,0.422,235.240,17.600,0.000,1.000,17.0
2006-12-16 17:39:00,3.384,0.282,237.140,14.200,0.000,0.000,17.0
2006-12-16 17:40:00,3.270,0.152,236.730,13.800,0.000,0.000,17.0
2006-12-16 17:41:00,3.430,0.156,237.060,14.400,0.000,0.000,17.0
2006-12-16 17:42:00,3.266,0.000,237.130,13.800,0.000,0.000,18.0
2006-12-16 17:43:00,3.728,0.000,235.840,16.400,0.000,0.000,17.0
2006-12-16 17:44:00,5.894,0.000,232.690,25.400,0.000,0.000,16.0
2006-12-16 17:45:00,7.706,0.000,230.980,33.200,0.000,0.000,17.0
2006-12-16 17:46:00,7.026,0.000,232.210,30.600,0.000,0.000,16.0
2006-12-16 17:47:00,5.174,0.000,234.190,22.000,0.000,0.000,17.0
2006-12-16 17:48:00,4.474,0.000,234.960,19.400,0.000,0.000,17.0
2006-12-16 17:49:00,3.248,0.000,236.660,13.600,0.000,0.000,17.0
2006-12-16 17:50:00,3.236,0.000,235.840,13.600,0.000,0.000,17.0
2006-12-16 17:51:00,3.228,0.000,235.600,13.600,0.000,0.000,17.0
2006-12-16 17:52:00,3.258,0.000,235.490,13.800,0.000,0.000,17.0
2006-12-16 17:53:00,3.178,0.000,235.280,13.400,0.000,0.000,17.0
...,...,...,...,...,...,...,...
2010-11-26 20:33:00,0.978,0.000,240.280,4.000,0.000,1.000,0.0
2010-11-26 20:34:00,0.968,0.000,237.570,4.000,0.000,1.000,0.0
2010-11-26 20:35:00,0.960,0.000,238.010,4.000,0.000,1.000,0.0
2010-11-26 20:36:00,0.964,0.000,238.070,4.000,0.000,1.000,0.0
2010-11-26 20:37:00,0.980,0.000,237.900,4.200,0.000,1.000,0.0
2010-11-26 20:38:00,0.976,0.096,236.970,4.000,0.000,2.000,0.0
2010-11-26 20:39:00,0.984,0.100,238.160,4.200,0.000,1.000,0.0
2010-11-26 20:40:00,0.986,0.102,238.920,4.200,0.000,1.000,0.0
2010-11-26 20:41:00,0.990,0.106,239.570,4.200,0.000,1.000,0.0
2010-11-26 20:42:00,0.988,0.106,239.600,4.200,0.000,1.000,0.0
2010-11-26 20:43:00,0.988,0.106,239.640,4.200,0.000,1.000,0.0
2010-11-26 20:44:00,0.982,0.102,238.690,4.000,0.000,1.000,0.0
2010-11-26 20:45:00,0.972,0.092,238.320,4.000,0.000,2.000,0.0
2010-11-26 20:46:00,0.908,0.000,238.530,3.800,0.000,1.000,0.0
2010-11-26 20:47:00,0.910,0.000,238.710,3.800,0.000,1.000,0.0
2010-11-26 20:48:00,0.912,0.000,239.250,3.800,0.000,1.000,0.0
2010-11-26 20:49:00,0.948,0.000,238.160,4.000,0.000,1.000,0.0
2010-11-26 20:50:00,1.198,0.128,238.110,5.000,0.000,1.000,0.0
2010-11-26 20:51:00,1.024,0.106,238.840,4.200,0.000,1.000,0.0
2010-11-26 20:52:00,0.946,0.000,239.050,4.000,0.000,0.000,0.0
2010-11-26 20:53:00,0.944,0.000,238.720,4.000,0.000,0.000,0.0
2010-11-26 20:54:00,0.946,0.000,239.310,4.000,0.000,0.000,0.0
2010-11-26 20:55:00,0.946,0.000,239.740,4.000,0.000,0.000,0.0
2010-11-26 20:56:00,0.942,0.000,239.410,4.000,0.000,0.000,0.0
2010-11-26 20:57:00,0.946,0.000,240.330,4.000,0.000,0.000,0.0
2010-11-26 20:58:00,0.946,0.000,240.430,4.000,0.000,0.000,0.0
2010-11-26 20:59:00,0.944,0.000,240.000,4.000,0.000,0.000,0.0
2010-11-26 21:00:00,0.938,0.000,239.820,3.800,0.000,0.000,0.0
2010-11-26 21:01:00,0.934,0.000,239.700,3.800,0.000,0.000,0.0
2010-11-26 21:02:00,0.932,0.000,239.550,3.800,0.000,0.000,0.0

In [38]:
dataset['Global_active_power'].describe()

count     2049280
unique       4186
top         0.218
freq         9565
Name: Global_active_power, dtype: object

In [39]:
dataset['Global_reactive_power'].describe()

count     2049280
unique        532
top         0.000
freq       481561
Name: Global_reactive_power, dtype: object

In [40]:
dataset['Voltage'].describe()

count     2049280
unique       2837
top       241.180
freq         3559
Name: Voltage, dtype: object

In [32]:
# remove '?' characters
import numpy as np
dataset.replace('?', np.nan, inplace=True)

In [47]:
# convert values to numeric
dataset = dataset.astype('float32')

In [48]:
dataset.dtypes

Global_active_power      float32
Global_reactive_power    float32
Voltage                  float32
Global_intensity         float32
Sub_metering_1           float32
Sub_metering_2           float32
Sub_metering_3           float32
dtype: object

In [49]:
dataset.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,1.091631e+00,1.237042e-01,2.433813e+02,4.629239e+00,1.121923e+00,1.298520e+00,6.458447e+00
std,1.057005e+00,1.128308e-01,4.114049e+00,4.440444e+00,6.104221e+00,5.758089e+00,8.458705e+00
min,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,0.000000e+00,0.000000e+00,1.000000e+00
75%,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,0.000000e+00,1.000000e+00,1.700000e+01
max,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.800000e+01,8.000000e+01,3.100000e+01

# Read in and adjust the data
## Fill in missing values with value at the same time one day prior

In [52]:
def fill_missing(values):
    import numpy as np
    one_day = 60 * 24
    for row in range(values.shape[0]):
        for col in range(values.shape[1]):
            if np.isnan(values[row, col]):
                values[row, col] = values[row - one_day, col]

In [53]:
# fill missing values
fill_missing(dataset.values)

## Add a column for the remainder of sub metering

In [55]:
values = dataset.values
dataset['sub_metering_4'] = (values[:,0] * 1000 / 60) - (values[:,4] + values[:,5] + values[:, 6])

# Save the adjusted data set

In [56]:
dataset.to_csv('household_power_consumption.csv')

End of notebook